.TH total 1 total\-0.0.1
.SH NAME
total \- sum of all lines in a file or standard in.
.SH SYNOPSIS
.B total [FILE]
.SH DESCRIPTION
.B total 
adds all lines in 
.B FILE
or standard in.
.SH OPTIONS
none
.SH EXAMPLES
.LP
.B echo '1
.br
.B 2
.br
.B 3' | total
.LP
yields
.LP
.B 6
.br
.SH SEE ALSO
.B awk(1)
.SH BUGS
Probably.
.SH LICENSE
\(co 2020 Noah Birnel
.sp
You may use this software however you like.
