#!/usr/bin/env python3

import argparse

import stats

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "infile",
        help="File to read.",
        nargs='?',
        metavar='FILE',
        default=sys.stdin,  
        type=argparse.FileType('r'),
        )
    args = parser.parse_args()
    infile = args.infile

    data = [stats.num_from_str(l) for l in infile.readlines()]

    print(stats.deviations(data))

if __name__ == "__main__":
    main()

