#!/usr/bin/env python3

import argparse
from math import factorial

import stats

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "number",
        help="number",
        type=stats.positive_int_from_str,
        )
    args = parser.parse_args()


    print(factorial(args.number))

if __name__ == "__main__":
    main()
