#!/usr/bin/env python3

import argparse
from math import floor

import stats

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "infile",
        help="File to read.",
        nargs='?',
        metavar='FILE',
        default=sys.stdin,  
        type=argparse.FileType('r'),
        )
    args = parser.parse_args()
    infile = args.infile

    data = [stats.num_from_str(l) for l in s.readlines()]

    print(stats.median(data))

if __name__ == "__main__":
    main()
