#!/usr/bin/env python3

import argparse

import stats

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "infile",
        help="File to read.",
        nargs='?',
        metavar='FILE',
        default=sys.stdin,  
        type=argparse.FileType('r'),
        )
    parser.add_argument(
        "-p",
        "--is-population",
        help="data are a population",
        action="store_false",
        default=True,
        dest="is_sample",
        )
    args = parser.parse_args()
    infile = args.infile
    is_sample=args.is_sample

    data = [stats.num_from_str(l) for l in infile.readlines()]

    print(stats.variance(data, is_sample=is_sample))

if __name__ == "__main__":
    main()
